In [1]:
#係數矩陣A、常數矩陣B、係數矩陣的反矩陣A_inv
#Ax=B
#A^(-1) Ax=A^(-1) B
#x=A^(-1) B

In [2]:
import numpy as np

## 3變數線性方程組

In [3]:
n = 3  # 變數個數
#n = np.random.randint(2,10)

np.random.seed(0)  # 設置seed使每次生成的隨機數相同
A = np.random.randint(-5, 5, size = (n,n))  # 產生nxn、數值範圍[-5,5)的係數矩陣A

np.random.seed(1)  # 設置seed使每次生成的隨機數相同
B = np.random.randint(-5, 5, size = (n,1))  # 產生nx1、數值範圍[-5,5)的常數矩陣B

## 解法一：
x = np.linalg.solve(A, B)  # 直接得出解矩陣x

print(
f'''
n = {n}, 
A = 
{A}
B = 
{B}
x = 
{x}
''')

np.isclose(A @ x, B)  # 驗算(A @ x == B)


n = 3, 
A = 
[[ 0 -5 -2]
 [-2  2  4]
 [-2  0 -3]]
B = 
[[0]
 [3]
 [4]]
x = 
[[-1.75806452]
 [ 0.06451613]
 [-0.16129032]]



array([[ True],
       [ True],
       [ True]])

In [4]:
## 解法二：
x1 = np.linalg.inv(A) @ B  # x=A^(-1) B
x1

array([[-1.75806452],
       [ 0.06451613],
       [-0.16129032]])

In [5]:
np.isclose(A @ x1, B)  # 驗算(A @ x1 == B)

array([[ True],
       [ True],
       [ True]])

## 5個變數線性方程組

In [6]:
n = 5  # 變數個數

np.random.seed(0)  # 設置seed使每次生成的隨機數相同
A = np.random.randint(-5, 5, size = (n,n))  # 產生nxn、數值範圍[-5,5)的係數矩陣A

np.random.seed(1)  # 設置seed使每次生成的隨機數相同
B = np.random.randint(-5, 5, size = (n,1))  # 產生nx1、數值範圍[-5,5)的常數矩陣B

x = np.linalg.solve(A, B)  # 直接得出解矩陣x

print(
f'''
n = {n}, 
A = 
{A}
B = 
{B}
x = 
{x}
''')

np.isclose(A @ x, B)  # 驗算(A @ x == B)


n = 5, 
A = 
[[ 0 -5 -2 -2  2]
 [ 4 -2  0 -3 -1]
 [ 2  1  3  3 -4]
 [ 1  2  2  3 -4]
 [ 0  4  3  4 -1]]
B = 
[[ 0]
 [ 3]
 [ 4]
 [ 0]
 [-5]]
x = 
[[-5.05357143]
 [-1.75      ]
 [ 7.30357143]
 [-5.66071429]
 [-2.73214286]]



array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

## 10個變數線性方程組

In [7]:
n = 10  # 變數個數

np.random.seed(0)  # 設置seed使每次生成的隨機數相同
A = np.random.randint(-5, 5, size = (n,n))  # 產生nxn、數值範圍[-5,5)的係數矩陣A

np.random.seed(1)  # 設置seed使每次生成的隨機數相同
B = np.random.randint(-5, 5, size = (n,1))  # 產生nx1、數值範圍[-5,5)的常數矩陣B

x = np.linalg.solve(A, B)  # 直接得出解矩陣x

print(
f'''
n = {n}, 
A = 
{A}
B = 
{B}
x = 
{x}
''')

np.isclose(A @ x, B)  # 驗算(A @ x == B)


n = 10, 
A = 
[[ 0 -5 -2 -2  2  4 -2  0 -3 -1]
 [ 2  1  3  3 -4  1  2  2  3 -4]
 [ 0  4  3  4 -1 -2 -5 -2  0 -5]
 [-3 -2  3 -4 -2 -2 -2  2 -5 -4]
 [ 4  4 -5 -1  2 -2 -3  2 -3 -5]
 [-5 -1  0  0  1  3 -1 -4 -1  4]
 [ 3 -4 -4  2  4  4 -2  1  2 -3]
 [-5 -2  0  4 -1 -1  1 -1 -1 -2]
 [-1 -1  3 -1 -2  2  0  0 -5 -4]
 [ 0  4 -2 -5  0 -5 -4 -3 -1 -3]]
B = 
[[ 0]
 [ 3]
 [ 4]
 [ 0]
 [-5]
 [-5]
 [-4]
 [ 2]
 [ 1]
 [ 4]]
x = 
[[ 2.41026587]
 [-2.33689728]
 [-0.30247412]
 [ 0.90538128]
 [-2.84414544]
 [-1.88566993]
 [-0.59590749]
 [-2.26735821]
 [-0.75324469]
 [ 0.69925056]]



array([[ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True],
       [ True]])